version: '3.8'

networks:
  jm-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: jobmanager
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobmanager
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - jm-network
    ports:
      - 9090:9090
  grafana: 
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - jm-network